language: java
jdk: openjdk8
os: linux
install:
  - nvm install node
  - node --version
  - npm --version
  - npm install aurelia-cli -g
  - cd ./src/main/javascript
  - npm install
  - cwd
  - node deploy -env prod
  - cwd
  - cd ../../..
deploy:
  - provider: heroku
    api_key: $HEROKU_API_KEY
    app: "graduate-admission-system"
    on:
      branch: master
  - provider: heroku
    api_key: $HEROKU_API_KEY
    app: "graduate-admission-staging"
    on:
      branch: crushton/frontend-prod-install