language: java
jdk:
  openjdk8
deploy:
  - provider: heroku
    api-key:
      secure: $HEROKU_API_KEY
    app: "graduate-admission-system"
    env: "dev"
    on:
      branch: crushton/single-app-deployment
  - provider: heroku
    api-key:
      secure: $HEROKU_API_KEY
    app: "graduate-admission-system"
    env: "prod"
    on:
      branch: master