language: java
jdk: openjdk8
os: linux
#before_deploy:
#  - nvm install node
#  - node --version
#  - npm --version
#  - npm install aurelia-cli -g
#  - cd ./src/main/javascript
#  - npm install
#  - |
#    if [[ $TRAVIS_BRANCH != $TRAVIS_PULL_REQUEST_BRANCH && $TRAVIS_BRANCH = 'master' ]]; then
#      au build --env prod
#    else
#      au build --env stage
#    fi
#    cp -RT dist ../resources/static
#    sudo chmod -R 755 ../resources/static
#  - cd ../resources/static
#  - ls -lart
#  - cd ../../../..
#  - mvn package
deploy:
  - provider: heroku
    api_key: $HEROKU_API_KEY
    app: "graduate-admission-system"
    on:
      branch: master
  - provider: heroku
    api_key: $HEROKU_API_KEY
    app: "graduate-admission-staging"
    on:
      branch: crushton/frontend-prod-install