language: java
jdk: openjdk8
os: linux
before_deploy:
  - nvm install node
  - node --version
  - npm --version
  - npm install aurelia-cli -g
  - cd ./src/main/javascript
  - npm install
  - au build --env prod
  - cp -RT dist ../resources/static
  - cd ../../..
deploy:
  - provider: heroku
    api_key: $HEROKU_API_KEY
    app: "graduate-admission-system"
    skip_cleanup: true
    on:
      branch: master
  - provider: heroku
    api_key: $HEROKU_API_KEY
    app: "graduate-admission-staging"
    skip_cleanup: true
    on:
      branch: develop