language: java
jdk: openjdk8
os: linux
deploy:
  - provider: heroku
    api_key: $HEROKU_API_KEY
    app: "graduate-admission-system"
    env: "prod"
    on:
      branch: crushton/single-app-deployment