package sysc4806.graduateAdmissions.model;

import lombok.*;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

/**
 * Represents a Term (4 month period)
 * Used to Store Deadlines and denote which Term is active
 *
 * @author Eric
 */
@Setter
@Getter
@NoArgsConstructor
@ToString
@EqualsAndHashCode
@Entity
public class Term {

    @Id
    @GeneratedValue
    private long id;
    private boolean active;
    private String deadline;
    private Season season;
    private String year;

    /**
     * Creates a Term with an autogenerated id and given parameters
     *
     * @param deadline String representing the deadline for this term
     * @param season Season determining the season of the term
     * @param year String representing the year of the term
     * @param active boolean showing if the term is active or not
     */
    public Term(String deadline, Season season, String year, boolean active){
        this.deadline = deadline;
        this.season = season;
        this.year = year;
        this.active = active;
    }
}
