package sysc4806.graduateAdmissions.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import java.util.ArrayList;
/**
 * Represents one of three possible users in the system (Student, Professor, or Admin)
 * Used to user details, credentials, and information.
 *
 * @author Kevin Sun
 */
@NoArgsConstructor
@AllArgsConstructor
@Data
@Entity
public class User {

    @Id
    @GeneratedValue
    private long id;
    private String firstName;
    private String lastName;
    private String email;
    private String password; 
    private Role role;
    private ArrayList<Interest> interests;
    private ArrayList<String> applications; 

    /**
     * Creates a User with an autogenerated id and given parameters
     *
     * @param firstname String represents the first name of the user
     * @param lastname String represents the last name of the user
     * @param mail String represents the email of the user
     * @param r Role represents the role of the user
     * @param interest Array List interest contains the chosen interests of the user
     * @param application ArrayList application contains all applications of the user
     */
    public User(String firstname, String lastname, String mail, String pass, Role r, ArrayList<Interest> interest, ArrayList<String> application){
        this.firstName = firstname;
        this.lastName = lastname;
        this.email = mail;
        this.password = pass;
        this.role = r;
        this.interests = interest;
        this.applications = application;
    }
}
