package sysc4806.graduateAdmissions.model;

import lombok.*;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import java.util.ArrayList;
/**
 * Represents one of three possible users in the system (Student, Professor, or Admin)
 * Used to user details, credentials, and information.
 *
 * @author Kevin Sun
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
public class User {

    @Id
    @GeneratedValue
	private long id;
    private String firstName;
    private Season lastName;
    private String email;
    private String password; 
	private String role;
	private ArrayList<String> interests;
	private ArrayList<String> applications; 

    /**
     * Creates a User with an autogenerated id and given parameters
     *
     * @param firstname String represents the first name of the user
     * @param lastname String represents the last name of the user
     * @param mail String represents the email of the user
     * @param r String represents the role of the user
     * @param ArrayList interest contains the chosen interests of the user
     * @param ArrayList application contains all applications of the user
     */
    public Term(String firstname, String lastname, String mail, String pass, String r, ArrayList<String> interest, ArrayList<String> application){
        this.firstName = firstname;
        this.lastName = lastname;
        this.email = mail;
        this.password = pass;
		this.role = r;
		this.interests = interest;
		this.applications = application;
    }
}